spring:
  application:
    name: auth-service
  mvc:
    servlet:
      path: /auth-service

server:
  port: 8099

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka