spring:
  application:
    name: user-service
  mvc:
    servlet:
      path: /user-service

server:
  port: 8098

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka