spring:
  application:
    name: order-service
  mvc:
    servlet:
      path: /order-service

server:
  port: 8096

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka